### PR TITLE
:lipstick: Gui/gui client and protocol

### PR DESCRIPTION
**Pull request by BxptisteM**
- Implemented the network handling of the client
- Implemented Callbacks for the command handling (still have some to make)
- Implemented the display of the world & the trantorians

### CODE REVIEW

**Review by Klayni — APPROVED** [review]

**Review by Quentintnrl — APPROVED** [review]

**Review by 6im0n — APPROVED** [review]
Goof for me ! :+1:

**Review by 6im0n — CHANGES_REQUESTED** [review]
It seems you have a compilation problem 
Review it and it's good ;)
image

**Review by Quentintnrl — CHANGES_REQUESTED** [review]
Move the .obj for the coding style and it will be good

**Comment by BxptisteM** [comment]
> It seems you have a compilation problem Review it and it's good ;) image

This compilation error is server related. There is the same error on main :sweat_smile:

**Comment by BxptisteM** [comment]
> Move the .obj for the coding style and it will be good

The obj files are the 3D models that are used to display the trantorians and the clouds of the game. So i can't really remove it. :sweat_smile:

**Comment by Quentintnrl** [comment]
@BxptisteM For the compilation error you can replace "&destroy_egg" by "(void *)&destroy_egg) it will fix the error

And for the assets you can move them in the tests directory at the root of the repo so they will be ignore by banana

**Review by Quentintnrl — APPROVED** [review]

**Review by RenardFute — APPROVED** [review]

**Pull request merged**
